package cn.swjtu.message.mapper;

import cn.swjtu.message.model.Performance;
import cn.swjtu.message.model.PerformanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PerformanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    long countByExample(PerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    int deleteByExample(PerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    int deleteByPrimaryKey(Integer perId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    int insert(Performance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    int insertSelective(Performance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    List<Performance> selectByExample(PerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    Performance selectByPrimaryKey(Integer perId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") Performance record, @Param("example") PerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    int updateByExample(@Param("record") Performance record, @Param("example") PerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    int updateByPrimaryKeySelective(Performance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    int updateByPrimaryKey(Performance record);
}