package cn.swjtu.message.model;

import java.io.Serializable;

public class Performance implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.per_id
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    private Integer perId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.per_name
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    private String perName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.per_grade_message
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    private Integer perGradeMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.per_group_tel
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    private Integer perGroupTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.per_group_agree
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    private Integer perGroupAgree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.per_group_logon
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    private Integer perGroupLogon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table performance
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.per_id
     *
     * @return the value of performance.per_id
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    public Integer getPerId() {
        return perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.per_id
     *
     * @param perId the value for performance.per_id
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    public void setPerId(Integer perId) {
        this.perId = perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.per_name
     *
     * @return the value of performance.per_name
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    public String getPerName() {
        return perName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.per_name
     *
     * @param perName the value for performance.per_name
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    public void setPerName(String perName) {
        this.perName = perName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.per_grade_message
     *
     * @return the value of performance.per_grade_message
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    public Integer getPerGradeMessage() {
        return perGradeMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.per_grade_message
     *
     * @param perGradeMessage the value for performance.per_grade_message
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    public void setPerGradeMessage(Integer perGradeMessage) {
        this.perGradeMessage = perGradeMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.per_group_tel
     *
     * @return the value of performance.per_group_tel
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    public Integer getPerGroupTel() {
        return perGroupTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.per_group_tel
     *
     * @param perGroupTel the value for performance.per_group_tel
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    public void setPerGroupTel(Integer perGroupTel) {
        this.perGroupTel = perGroupTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.per_group_agree
     *
     * @return the value of performance.per_group_agree
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    public Integer getPerGroupAgree() {
        return perGroupAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.per_group_agree
     *
     * @param perGroupAgree the value for performance.per_group_agree
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    public void setPerGroupAgree(Integer perGroupAgree) {
        this.perGroupAgree = perGroupAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.per_group_logon
     *
     * @return the value of performance.per_group_logon
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    public Integer getPerGroupLogon() {
        return perGroupLogon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.per_group_logon
     *
     * @param perGroupLogon the value for performance.per_group_logon
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    public void setPerGroupLogon(Integer perGroupLogon) {
        this.perGroupLogon = perGroupLogon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated Mon Nov 30 09:48:03 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", perId=").append(perId);
        sb.append(", perName=").append(perName);
        sb.append(", perGradeMessage=").append(perGradeMessage);
        sb.append(", perGroupTel=").append(perGroupTel);
        sb.append(", perGroupAgree=").append(perGroupAgree);
        sb.append(", perGroupLogon=").append(perGroupLogon);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}